"""
Security configuration for the Python code executor.
"""

# List of allowed modules that can be imported safely
ALLOWED_MODULES = [
    'math',
    'random',
    'datetime',
    'time',
    'json',
    'base64',
    'hashlib',
    'uuid',
    'itertools',
    'functools',
    'collections',
    'operator',
    'string',
    're',
    'calendar',
    'decimal',
    'fractions',
    'statistics',
]

# Restricted names that should not be accessible
RESTRICTED_NAMES = [
    'open',
    'file',
    'input',
    'raw_input',
    'eval',
    'exec',
    'compile',
    '__import__',
    'reload',
    'exit',
    'quit',
    'help',
    'license',
    'credits',
    'copyright',
    'globals',
    'locals',
    'vars',
    'dir',
    'getattr',
    'setattr',
    'delattr',
    'hasattr',
    '__file__',
    '__name__',
    '__doc__',
    '__package__',
]

# Restricted modules that should never be imported
RESTRICTED_MODULES = [
    'os',
    'sys',
    'subprocess',
    'shutil',
    'tempfile',
    'glob',
    'fnmatch',
    'linecache',
    'pickle',
    'shelve',
    'marshal',
    'anydbm',
    'whichdb',
    'dumbdbm',
    'socket',
    'urllib',
    'urllib2',
    'httplib',
    'ftplib',
    'imaplib',
    'poplib',
    'smtplib',
    'telnetlib',
    'SocketServer',
    'BaseHTTPServer',
    'SimpleHTTPServer',
    'CGIHTTPServer',
    'cookielib',
    'Cookie',
    'threading',
    'thread',
    'multiprocessing',
    'imp',
    'importlib',
    'ctypes',
]
